import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { UtensilsCrossed, ArrowRight } from "lucide-react";
export const metadata: Metadata = { title: "Claim Your Caribbean Restaurant Listing | VakayGo", description: "Help travelers discover your restaurant. Claim your VakayGo listing and update your cuisine, opening hours, location, photos and contact details for free." };
export default function ForRestaurantsPage() {
  return <><Header /><main className="bg-cream-50 pt-28 pb-20"><section className="mx-auto max-w-4xl px-6 py-12"><UtensilsCrossed size={36} className="text-gold-700" /><p className="mt-6 text-sm font-bold uppercase tracking-widest text-gold-700">For Caribbean restaurants</p><h1 className="mt-4 max-w-3xl text-4xl md:text-6xl font-bold text-navy-800" style={{ fontFamily: "var(--font-display)" }}>Help travelers find a place at your table.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-navy-500">Start with accurate information. Claim your restaurant’s listing, verify ownership, and show visitors what makes your food and setting worth discovering.</p><Link href="/for-businesses#find-listing" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-gold-700 px-6 py-3 font-semibold text-white">Find and claim my restaurant<ArrowRight size={18} /></Link><p className="mt-3 text-sm text-navy-500">Free to claim. Bookings and payments are currently unavailable.</p></section>
  <section className="mx-auto max-w-4xl px-6"><h2 className="text-3xl font-bold text-navy-800">Give diners the details they need</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{[
    ["Cuisine and menu information", "Describe the food you serve and keep any menu details accurate. Include dietary options only when your team can provide them."],
    ["Opening hours", "Check regular hours and update them for seasonal changes or closures. Travelers should confirm current hours directly with you."],
    ["Location and contact", "Review your address, phone number and official website so visitors can find the right business."],
    ["Photos and atmosphere", "Use photos you have the right to share. Show the dining space and food visitors can expect to find."],
  ].map(([title, body]) => <article key={title} className="rounded-2xl border border-cream-200 bg-white p-7"><h3 className="text-xl font-bold text-navy-800">{title}</h3><p className="mt-3 leading-relaxed text-navy-500">{body}</p></article>)}</div></section>
  <section className="mx-auto max-w-4xl px-6 pt-12"><h2 className="text-2xl font-bold text-navy-800">Can diners reserve a table through this listing?</h2><p className="mt-3 leading-relaxed text-navy-500">VakayGo is currently a directory. Travelers can read your restaurant’s information and record interest, but that does not reserve a table or request availability. Booking features require separate onboarding and activation.</p><h2 className="mt-8 text-2xl font-bold text-navy-800">How do I claim my restaurant?</h2><p className="mt-3 leading-relaxed text-navy-500"><Link className="text-gold-700 underline" href="/for-businesses#find-listing">Search for your existing listing</Link>, confirm the location, and create a business account. Verify your email and follow the ownership verification steps. If the contact details are wrong or you need help, <Link className="text-gold-700 underline" href="/contact">contact VakayGo</Link>.</p></section>
  </main><Footer /></>;
}
